# Generated by Django 4.1 on 2022-11-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("answer_idx", models.AutoField(primary_key=True, serialize=False)),
                ("intent_1", models.CharField(blank=True, max_length=10, null=True)),
                ("intent_2", models.CharField(blank=True, max_length=10, null=True)),
                ("ner", models.CharField(blank=True, max_length=20, null=True)),
                ("answer", models.CharField(blank=True, max_length=100, null=True)),
                ("answer_contents", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "answer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_idx", models.AutoField(primary_key=True, serialize=False)),
                ("metro_code", models.IntegerField(blank=True, null=True)),
                ("metro", models.CharField(blank=True, max_length=50, null=True)),
                ("location_code", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
                ("q", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "location",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                ("members_idx", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(blank=True, max_length=30, null=True)),
                ("pw", models.CharField(blank=True, max_length=50, null=True)),
                ("m_name", models.CharField(blank=True, max_length=30, null=True)),
                ("addr", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "m_location",
                    models.CharField(
                        blank=True, default="NULL", max_length=10, null=True
                    ),
                ),
                ("m_state", models.IntegerField(blank=True, default="NULL", null=True)),
                (
                    "m_answer",
                    models.CharField(
                        blank=True, default="NULL", max_length=10, null=True
                    ),
                ),
            ],
            options={
                "db_table": "members",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MemberLocation",
            fields=[
                ("ml_idx", models.AutoField(primary_key=True, serialize=False)),
                (
                    "location_list",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "m_idx",
                    models.ForeignKey(
                        blank=True,
                        db_column="m_idx",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BYEOLZZI.members",
                    ),
                ),
            ],
            options={
                "db_table": "member_location",
                "managed": True,
            },
        ),
    ]
