# Generated by Django 4.1 on 2022-11-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BYEOLZZI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="m_location",
            field=models.CharField(
                blank=True, default="NULL", max_length=10, null=True
            ),
        ),
    ]
